# Generated by Django 5.0.1 on 2025-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha en que se realizará la cita', verbose_name='Fecha de la cita')),
                ('time', models.TimeField(help_text='Hora en que se realizará la cita', verbose_name='Hora de la cita')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó')], default='scheduled', max_length=20, verbose_name='Estado de la cita')),
                ('reason', models.TextField(help_text='Descripción del motivo de la cita', verbose_name='Motivo de la consulta')),
                ('notes', models.TextField(blank=True, help_text='Notas o comentarios adicionales sobre la cita', verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['date', 'time'],
            },
        ),
    ]
