# Generated by Django 5.0.1 on 2025-11-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
        ('doctors', '0004_alter_doctor_options_and_more'),
        ('patients', '0004_patient_patients_pa_status_ca3fc5_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['reason'], name='appointment_reason_0236f1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['notes'], name='appointment_notes_def2c1_idx'),
        ),
    ]
