# Generated by Django 5.0.1 on 2025-09-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaryprofile',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Permiso para acceder a reportes y estadísticas', verbose_name='Puede Ver Reportes'),
        ),
        migrations.AddField(
            model_name='secretaryprofile',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Fecha en que fue contratada la secretaria', null=True, verbose_name='Fecha de Contratación'),
        ),
    ]
