# Generated by Django 5.0.1 on 2025-11-24 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Tipo de acción realizada (create, update, delete, view)', max_length=100, verbose_name='Acción')),
                ('resource', models.CharField(help_text='Tipo de recurso afectado (appointments, patients, users, etc.)', max_length=100, verbose_name='Recurso')),
                ('resource_id', models.CharField(blank=True, help_text='ID específico del recurso afectado', max_length=50, null=True, verbose_name='ID del Recurso')),
                ('method', models.CharField(help_text='Método HTTP utilizado (GET, POST, PUT, DELETE)', max_length=10, verbose_name='Método HTTP')),
                ('path', models.CharField(help_text='Ruta completa de la petición', max_length=500, verbose_name='Ruta')),
                ('ip_address', models.GenericIPAddressField(help_text='Dirección IP desde donde se realizó la petición', verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente', verbose_name='User Agent')),
                ('request_data', models.JSONField(blank=True, help_text='Datos enviados en la petición (sin información sensible)', null=True, verbose_name='Datos de la Petición')),
                ('response_status', models.IntegerField(blank=True, help_text='Código de estado HTTP de la respuesta', null=True, verbose_name='Estado de la Respuesta')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Momento en que se realizó la acción', verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_user_time_idx'), models.Index(fields=['action', 'timestamp'], name='audit_action_time_idx'), models.Index(fields=['resource', 'timestamp'], name='audit_resource_time_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_ip_time_idx')],
            },
        ),
    ]
