# Generated by Django 5.0.1 on 2025-09-22 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo de sangre')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('medical_conditions', models.TextField(blank=True, null=True, verbose_name='Condiciones médicas')),
                ('medications', models.TextField(blank=True, null=True, verbose_name='Medicamentos actuales')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del contacto de emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del contacto de emergencia')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relación con el contacto de emergencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
