# Generated by Django 5.0.1 on 2025-11-24 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_add_patient_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status'], name='patients_pa_status_ca3fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user'], name='patients_pa_user_id_b78fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['emergency_contact_phone'], name='patients_pa_emergen_2a7e17_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['emergency_contact_name'], name='patients_pa_emergen_e14267_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['address'], name='patients_pa_address_9f5444_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='patients_pa_created_542792_idx'),
        ),
    ]
