# Generated by Django 5.0.1 on 2025-09-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('disabled', 'Inhabilitado')], default='active', help_text='Estado actual del doctor en el sistema', max_length=20, verbose_name='Estado'),
        ),
    ]
