# Generated by Django 5.0.1 on 2025-11-24 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['created_at'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialization'], name='doctors_doc_special_037046_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['status'], name='doctors_doc_status_d677b8_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_available'], name='doctors_doc_is_avai_e473c5_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['created_at'], name='doctors_doc_created_04e2c9_idx'),
        ),
    ]
