# Generated by Django 5.0.1 on 2025-11-10 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_add_sale_amount_to_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
