# Generated by Django 5.0.1 on 2025-11-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_price_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
