# Generated by Django 5.0.1 on 2025-11-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_add_reserved_to_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
