# Generated by Django 5.0.1 on 2025-11-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_inventory_reserved_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(default='main', max_length=120),
        ),
    ]
