# Generated by Django 5.0.1 on 2025-11-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_inventory_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='min_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
