# Generated by Django 5.0.1 on 2025-11-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_add_favorite_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='inventory_reserved_stock_not_exceed_stock',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='inventory_non_negative',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='address_user_default_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cartitem_cart_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orderitem_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='price',
            name='price_active_product_valid_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_active_cat_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='productimage_product_position_idx',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
