# Generated by Django 5.0.1 on 2025-11-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_cartitem_created_at_cartitem_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
    ]
