# Generated by Django 5.0.1 on 2025-11-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_add_provider_to_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='mock', max_length=30),
        ),
    ]
