# Generated by Django 5.0.1 on 2025-11-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_orderitem_subtotal_alter_payment_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('badge', models.CharField(blank=True, default='Oferta', max_length=50)),
                ('cta_text', models.CharField(blank=True, default='Ver productos en oferta', max_length=80)),
                ('cta_link', models.CharField(blank=True, default='/pharmacy/offers', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
